### ISSUE TITLE
QLC+ project

### ISSUE THREAD

**Issue by chemicstry** [scheb/sound-to-light-osc#7]
Hey, I think this is a really cool project. I was quite surprised that there are so few sound to light DMX solutions. The only other that worked fine is soundswitch, but it's subscription based, yuck.

Anyway, I was wondering if you could share your QLC project to see how you wired the OSC signals? I managed to connect a single button to flash lights on beat, but I'm not sure how to setup different behavior for different programs.

P.S. if you're still interested in working on this project, I recommend trying https://github.com/CPJKU/madmom for beat detection. It uses neural networks and works surprisingly well in online mode.

**Comment by scheb** [comment]
This is what I'm using: [qlcplus.zip](https://github.com/scheb/sound-to-light-osc/files/10146157/qlcplus.zip)

The key part is, I have all the chasers in a red frame, so that only _one_ of them can be active. The `/prog*` signals are switching to the respective chaser. Since they're all in that red frame, the previously active chaser is automatically stopped. And on the `/beat` or `/bar` signal the chasers proceed through the different scenes.

![grafik](https://user-images.githubusercontent.com/1259952/205436034-8832a90a-c81f-4fe7-a3af-336b6bfaf8c6.png)

**Comment by chemicstry** [comment]
Thanks!
