### ISSUE TITLE
Higher BPM

### ISSUE THREAD

**Issue by deckenventilator24** [scheb/sound-to-light-osc#8]
Hey, usefull project of yours but it seams to have difficulties with higher BPMs. If I raise the value of max BPM in bpm.py the hole beat detection is of. Is there a way to get it working with up to 200 BPM?

**Comment by scheb** [comment]
Hi, thanks for reaching out. I've put this script together based on some other library and modified it for my own use case several years ago. For that it was working fine, but it did not require these higher BPM. In the meantime I've also forgot about most of it's inner workings 😬

You'd probably need to dive into the beat detection algorithm. As far as I remember the BPM cap is there, because the detection algorithm has this issue. It is a simple "fix" to achieve better detection by forcing the BPM into a certain range. Can't tell you what's exactly wrong with the algorithm on higher BPM, I've never bothered investigating it.

**Comment by marm1te** [comment]
Hi there, I plan to use your beat detection implementation. But I will replace your numpy fft generation with the one from tensorflow (which won't work out of the box...but will once I adapt it).

I do not think your program needs it, if you just use your code. But if you run it next to an inference model it helps to consolidate the ffts to one time and makes it fast and near real time on gpu.

tell me if you want me to share the updates with you. :)

**Comment by scheb** [comment]
@marm1te  No thanks, I'd keep it as is, because it would break my use-case (or at least make it more complicated than necessary). Feel free to create a fork to customize it for your purposes. That why it's here on GitHub, in case someone finds it helpful :)
